### PR TITLE
Feature/new UI theme - Settings page, Delete Podcast Confirmation modal, User Administration page, Change Role modal, Create Invite modal

### PR DESCRIPTION
**Pull request by jchue**
### Description

This is the fourth PR for #158 and includes the redesign of the Settings page (along with the Delete Podcast Confirmation modal) and the Administration page, which has been renamed to "User Administration" (along with the Change Role and Create Invite modals). It also includes the following changes:

- I made further adjustments to the z-index values, since I discovered an issue when a Radix component is inside a modal.
- The volume icon was supposed to change based on the current volume, but I didn't account for values > 100. I've changed it to a percentage calculation.
- Miscellaneous renaming of files:
  - `ui/src/components/ButtonPrimary.tsx` > `ui/src/components/CustomButtonPrimary.tsx`
  - `ui/src/components/ButtonSecondary.tsx` > `ui/src/components/CustomButtonSecondary.tsx`
  - `ui/src/components/UserPromoteModal.tsx` > `ui/src/components/ChangeRoleModal.tsx`
  - `ui/src/components/AddInvite.tsx` > `ui/src/components/CreateInviteModal.tsx`
  - `ui/src/pages/SettingsPage.tsx` split out to component `ui/src/components/SettingsData.tsx`
  - `ui/src/components/OPMLExport.tsx` > `ui/src/components/SettingsOPMLExport.tsx`
  - `ui/src/components/PodcastNaming.tsx` > `ui/src/components/SettingsNaming.tsx`
  - `ui/src/components/PodcastDelete.tsx` > `ui/src/components/SettingsPodcastDelete.tsx`
  - `ui/src/pages/AdministrationPage.tsx` > `ui/src/pages/UserAdminPage.tsx`
  - `ui/src/pages/AdministrationUserPage.tsx`  converted to component `ui/src/components/UserAdminUsers.tsx`
  - `ui/src/pages/InviteAdministrationUserPage.tsx` converted to component `ui/src/components/UserAdminInvites.tsx`

### Linked Issues

This addresses part but not all of #158.

### Additional context

- I've converted what used to be two separate user/invite administration pages into a single page with tabs.
- I've added the explicit consent switch and completed the "change role" modal. I think this is worth double-checking to confirm I did it correctly.

### CODE REVIEW

**Comment by SamTV12345** [comment]
I get this output in the console:

[vite:css] Gradient has outdated direction syntax. New syntax is like `closest-side at 0 0` instead of `0 0, closest-side`.
58 |  /* Applies horizontal scrolling shadows for smaller screens (https://lea.verou.me/2012/04/background-attachment-local/) */
59 |  .scrollbox-x {
60 |      background:
   |       ^
61 |  
62 |          /* Shadow covers */

**Comment by SamTV12345** [comment]
At some point when scrolling I get an error in the timeline saying Invalid "number" argument: NaN when TimeAgo is trying to parse a date. Maybe set that date to the beginning of unix time so we don't get an exception.

**Comment by SamTV12345** [comment]
I noticed when going through the naming conventions tab that the podcast detailed page could need a feedback for the user when clicking the download icon. I tapped two times because I though nothing would happen.

**Comment by SamTV12345** [comment]
When deleting a podcast via the UI, the entry needs to be deleted after the backend deleted files/database entries.

**Comment by jchue** [comment]
> I get this output in the console...

Thanks, fixed.

> At some point when scrolling I get an error in the timeline saying Invalid "number" argument: NaN when TimeAgo is trying to parse a date. Maybe set that date to the beginning of unix time so we don't get an exception.

I can't seem to reproduce this. Perhaps it's data-specific to the podcasts to which you're subscribed? When you say "Maybe set that date to the beginning of unix time," do you mean set a default in `formatTime()`?

> I noticed when going through the naming conventions tab that the podcast detailed page could need a feedback for the user when clicking the download icon. I tapped two times because I though nothing would happen.

Sorry about that. It should be fixed now.

> When deleting a podcast via the UI, the entry needs to be deleted after the backend deleted files/database entries.

I think that's how it is in the existing build. Nevertheless, I have implemented this.

**Comment by SamTV12345** [comment]
Thanks. It could be that I forgot to add that functionality. Thanks for the pull request. Looks good.

**Pull request merged**
