### PR TITLE
Feature/new UI theme - Sidebar, header, responsive new pages

### PR DESCRIPTION
**Pull request by jchue**
### Description

This is the second iteration of #158. This PR applies the updated design to the sidebar and header. It also updates the pages that were addressed in #176 to make them responsive.

### Linked Issues

This addresses part but not all of #158.

### Additional context

- Making the grids responsive was a bit crazy. I hope the way I formatted the class names is alright; it made it easier to organize the breakpoints.
- The styling for the sidebar was a little disorganized. I tried to clean it up by using standard Tailwind class names as much as possible and then consolidating the rest in a central spreadsheet. But let me know if you would prefer to have separate spreadsheets corresponding to the respective components.

### CODE REVIEW

**Comment by SamTV12345** [comment]
Wow that was fast. 

I only noticed a few things:

image
The scrollbar has the wrong color or is this extra xD. 
I don't know if you can do that can you make the items in the dropdown disappear in an animation and the notification next to it slides up. If not it is not a problem. Just got to my mind.

In the french version the All subscriptions page is overflowing. Maybe break words when it overflows.
image

I think it would be good that when I tap on this 
image
that the sidebar collapses.

**Comment by jchue** [comment]
> I think it would be good that when I tap on this image that the sidebar collapses.

When the sidebar is open and the user clicks on the "Add new" button, do you want the sidebar to collapse _and_ the Add New modal to open? Or would the user need to click twice (once to close the sidebar and again on the button to open the modal)?

**Comment by jchue** [comment]
> Or would the user need to click twice (once to close the sidebar and again on the button to open the modal)?

Assuming this is the case, I've made the requested changes.

**Comment by SamTV12345** [comment]
Perfect. Exactly what I meant. You're awesome 👏

**Pull request merged**
