### PR TITLE
Added Spanish translation

### PR DESCRIPTION
**Pull request by pablo-colilla**
### Description

Added Spanish translation.

### Additional context

I couldn't properly test the translations as I don't have a proper rust/cargo environment set. I hope the changes were easy enough so I didn't make any mistake.  Hopefully this translation is valuable for your application.

This is my first PR so please let me know if there is anything I missed.

### CODE REVIEW

**Comment by SamTV12345** [comment]
Thanks for the pull request. We just merged a new UI of the podcast server. As a result some translations changed. If you have the time please translate the following keys. I merged the current main branch into your branch so you can try the new ui.

The following are new:
- add-new
- all-subscriptions
- auto-clean is now auto-cleanup
- available-episodes
- copy-link
- create
- create-account
- data-retention
- delete
- delete-podcast-confirm
- delete-podcast-without-files
- episode-downloaded-to-server
- export-with-local-urls
- export-with-online-urls
- hardware
- invite-created
- invite-deleted
- invite-expires-at
- invite-link-copied
- latest-episodes
- no-results-found-for
- replace-invalid-characters-description
- search
- search-episodes
- sort-by
- system-configuration
- system-info
- use-existing-filenames
- user-deleted
- view-more

**Comment by pablo-colilla** [comment]
Sure. I will translate the labels with the keys above and get back when they are ready.

**Comment by SamTV12345** [comment]
I added more labels for the explanations in the settings menu. The labels are:
  - days-to-keep-explanation
  - auto-update-explanation
  - number-of-podcasts-to-download-explanation
  - auto-download-explanation
  - standard-episode-format-explanation
  - standard-podcast-format-explanation
  - colon-replacement-explanation

**Comment by pablo-colilla** [comment]
I did something wrong on my side when I tried to get the latest changes to my branch. Still newbie with this.

I have a copy. I will translate the new keys and get back with a new version.

I will get back with the Spanish translated version

**Comment by pablo-colilla** [comment]
Hopefully now everything is all right. Let me know otherwise.

**Comment by SamTV12345** [comment]
Thanks. It's now perfect. I readded Spanish in dropdown.

**Pull request merged**
